name: publish
on:
  release:
    types: [published]

jobs:
  publish:
    name: publish

    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: node setup
        uses: actions/setup-node@v3
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org

      - name: install bun
        shell: bash
        run: curl https://bun.sh/install | bash
      - name: setup bun PATH
        shell: bash
        run: |
          echo home/runner/.bun/bin/bun >> $GITHUB_PATH
          echo $GITHUB_WORKSPACE
      - name: install dependencies
        run: bun install
      - name: build package
        run: bun run build
      # - name: run test suites
      #   run: npm test

  #        export BUN_INSTALL="/home/runner/.bun"
          # echo PATH="$GITHUB_WORKSPACE/.bun/bin:$PATH" >> $GITHUB_PATH
  #  export PATH="$BUN_INSTALL/bin:$PATH"

      - name: publish
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
